export const SET_CURRENT_WEATHER = "SET_CURRENT_WEATHER";
export const SET_WEATHER_FORECAST = "SET_WEATHER_FORECAST";
export const FACEBOOK_LOGIN_FAILED = "FACEBOOK_LOGIN_FAILED";
export const FACEBOOK_LOGIN_SUCCESS = "FACEBOOK_LOGIN_SUCCESS";
